refactor(profiles): rename Profile to ProfileManifest and update related functions
veraison/corim pull request #140
Opened 2024-12-24 10:52 UTC by Priyanshuthapliyal2005

This pull request refactors the Profile struct to ProfileManifest across the codebase to resolve name collisions and improve code clarity.

Changes Made
Renamed the Profile struct to ProfileManifest in:
profiles.go
profiles_test.go
Related methods and variables.
Updated function signatures and internal references to align with the new struct name.
Ensured compatibility with all test cases, and verified that all tests pass successfully.

Why This Change Was Made
The previous implementation used the name Profile for both:
A variable representing eat.Profile (used as a ProfileID).
A struct that associates an eat.Profile with extensions.
This caused name collisions and confusion. Renaming the struct to ProfileManifest resolves these issues and aligns with naming conventions.

Testing
Ran the entire test suite using go test ./... and confirmed all tests passed.
Validated that no functionality was broken after the refactor.
Issue Fixed
This pull request fixes #135

2024-12-24 17:49 UTC, deeglaze commented
Please open an issue to discuss what the problem is. I’m at first concerned about the conflation of EAT and CoRIM that already exists in the codebase, so there is a broader conversation to be had.

2025-01-08 11:59 UTC, setrofim requested changes
Please also update `example_profile_test.go` with the name change (i.e. rename the local `profile` to `profileManifest`, etc).

2025-01-08 11:59 UTC, setrofim commented on corim/profiles.go
> +func GetProfile(id *eat.Profile) (ProfileManifest, bool) {
Should be renamed to `GetProfileManifest`

2025-01-08 17:59 UTC, Priyanshuthapliyal2005 commented
hi @setrofim , thank you for your feedback. I have rename the methods to GetProfileManifest to better reflect their functionality.

2025-01-08 18:00 UTC, setrofim approved these changes

2025-01-19 16:19 UTC, Priyanshuthapliyal2005 commented
Hi @setrofim,

Could you please help merge [this PR](https://github.com/veraison/corim/pull/140)? All checks have passed and the PR has been approved by you.

Thank you!

2025-01-20 08:30 UTC, merged